CREATE TABLE reports (
    id INT AUTO_INCREMENT PRIMARY KEY,
    school_id INT NOT NULL,
    type VARCHAR(100) NOT NULL,
    data JSON,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE
);